### PR TITLE
site redesign

### PR DESCRIPTION
**Pull request by zeospec**
Preview link:

https://bangpypers.netlify.com/

While pushing the site to production `url` in `config.yml` should be changed to `bangalore.python.org.in`

Recommended to provision lets encript certificate if possible.

https://jekyllrb.com/docs/continuous-integration/travis-ci/

### CODE REVIEW

**Comment by anistark** [comment]
@zeospec What else is pending in this?

**Comment by zeospec** [comment]
@anistark nothing that I could think off right now, there is one change which I am unclear about.

The past URL scheme had `/blog/2018/11/17/nov-workshop-report/` new site will have `/2018/11/17/nov-workshop-report/`.

I do recognise that the links will break but after looking at the importance and the SEO or current site, it seem irrelavent

**Comment by zeospec** [comment]
Having said that, the changes can be made to match that as well.

**Comment by anistark** [comment]
In that case, let's match it with the old one. Better not to have any broken links.

**Comment by zeospec** [comment]
> In that case, let's match it with the old one. Better not to have any broken links.

I'll do it today and push the changes today

**Comment by zeospec** [comment]
> In that case, let's match it with the old one. Better not to have any broken links.

Done updated the config to match the urls

**Pull request merged**
